### ISSUE TITLE
How to change font-family ?

### ISSUE THREAD

**Issue by raphaelgoetter** [Jacse/themes-for-brackets#96]
Hello,

I'm using Themes for Brackets for a few days ("Ambiance" theme) and it fits me well.

I just liked to change the font-family to Consolas. I opened and modified the /themes/ambiance.css to begin with : 

``` css
body {font-family: consolas, monospace;}
```

But nothing changes.

Is there a way to customize themes ?
